//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCueClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club_details
    {
        public int id { get; set; }
        public string Club_name { get; set; }
        public string Club_code { get; set; }
        public string address { get; set; }
        public string mobile_no { get; set; }
        public string Club_group { get; set; }
    }
}
