//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCueClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class customer_details
    {
        public int id { get; set; }
        [Display(Name = "Customer ID")]
        public string Customer_id { get; set; }
        [Display(Name ="Customer Name")]
        public string Customer_name { get; set; }
        [Display(Name = "Mobile")]
        [RegularExpression(@" ^[0-9]{10}$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public string mobile_no { get; set; }
        [Display(Name = "Opening Balance")]
        public Nullable<decimal> opening_balance { get; set; }
        public Nullable<int> for_cust_id { get; set; }
    }
}
