//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCueClub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Login_Details
    {
        public int id { get; set; }
        //[Display(Name = "User Name")]
        [Display(Name = "Name")]
        public string User_name { get; set; }
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        public string Email { get; set; }
        public string Password { get; set; }
        public string user_id { get; set; }
        public Nullable<int> for_user { get; set; }
        [Display(Name = "Mobile")]
        [RegularExpression(@"^[6-9]\d{9}$", ErrorMessage = "Please Enter Mobile No")]
        public string mobile_no { get; set; }
        [Display(Name = "User Role")]
        public string User_role { get; set; }
        [Display(Name = "Master User")]
        public string Master_user { get; set; }
       
    }
}
